name: bucketlist
favicon: null
layout_spectrum: 0.2959835573565215
typography_spectrum: 0.4656143239699304
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.11355951731093228
  lightness: 0.13693893468007445
  saturation: 0.19692475674673915
  rhythmicContrast: 0.2600022533442825
purpose: []
